// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication3.Data;

namespace WebApplication3.Data.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20201201190612_UpdateToDo")]
    partial class UpdateToDo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("WebApplication3.Models.ToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ToDos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2020, 12, 1, 11, 6, 12, 68, DateTimeKind.Local).AddTicks(2856),
                            Description = "Bake Cookies",
                            IsComplete = false,
                            Priority = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2020, 12, 1, 11, 6, 12, 74, DateTimeKind.Local).AddTicks(4993),
                            Description = "Eat Cookies",
                            IsComplete = false,
                            Priority = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2020, 12, 1, 11, 6, 12, 74, DateTimeKind.Local).AddTicks(5089),
                            Description = "Run around the block",
                            IsComplete = false,
                            Priority = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
